- name : Create and do something with pool
  hosts: proxmoxmain
  gather_facts: false
  tasks:
    - name: Create new Proxmox VE pool
      community.proxmox.proxmox_pool:
        api_host: pve01
        api_user: root@pam
        api_password: Nutanix/4u
        poolid: hoangnh
        comment: 'New pool create by ansible'

    # - name: Delete the Proxmox VE pool
    #   community.proxmox.proxmox_pool:
    #     api_host: pve02
    #     api_user: root@pam
    #     api_password: Nutanix/4u
    #     poolid: test
    #     state: absent


- name: Add or Remove MV from pool
  hosts: proxmoxmain
  gather_facts: true
  tasks:
    - name: Add new VM to Proxmox VE pool
      community.proxmox.proxmox_pool_member:
        api_host: pve01
        api_user: root@pam
        api_password: Nutanix/4u
        poolid: modopho
        type: vm
        member: "{{ item }}"
      loop:
          - "143"
          - "144"
          - "145"
#     - name: Add new storage to Proxmox VE pool
#       community.proxmox.proxmox_pool_member:
#         api_host: node1
#         api_user: root@pam
#         api_password: password
#         poolid: test
#         member: zfs-data
#         type: storage

#     - name: Remove VM from the Proxmox VE pool using VM name
#       community.proxmox.proxmox_pool_member:
#         api_host: node1
#         api_user: root@pam
#         api_password: password
#         poolid: test
#         member: pxe.home.arpa
#         state: absent

#     - name: Remove storage from the Proxmox VE pool
#       community.proxmox.proxmox_pool_member:
#         api_host: node1
#         api_user: root@pam
#         api_password: password
#         poolid: test
#         member: zfs-storage
#         type: storage
#         state: absent
