- name: Configure Proxmox network interfaces
  hosts: proxmox_nodes
  become: yes
  vars:
     vmbr0_ip: 10.200.8.21/24
  tasks:
    - name: Upload interfaces config
      template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644

    - name: Restart networking (Debian/Ubuntu)
      ansible.builtin.systemd:
        name: networking
        state: restarted
      when: ansible_os_family == "Debian"
